name: Release Backup Pvc
on:
  workflow_dispatch:
  #test
  push:
    branches:
      - feat_backup_ci

jobs:
  build-and-release-backup:
    name: Release Backup Pvc, build and push newest image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the e2e image
        #working-directory: backup/pvc 
        run: make -C backup/pvc docker-build-e2e

      - name: Run the e2e tests
        run: make -C backup/pvc docker-e2e

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Bump the version
        run: make -C backup/pvc docker-e2e sembump && make -C backup/pvc docker-e2e bump-version

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push the image to DockerHub
        run: |
          git reset --hard
          make -C backup/pvc docker-release
